service: quest-bank

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  versionFunctions: false

  environment:
    TABLE_NAME: ${file(./serverless.env.yml):dev.SLACK_TABLE_NAME}
    QUESTS_TABLE_NAME: ${file(./serverless.env.yml):dev.QUESTS_TABLE_NAME}
    USER_SETTINGS_TABLE_NAME: ${file(./serverless.env.yml):dev.USER_SETTINGS_TABLE_NAME}
    OAUTH_ACCESS_TOKEN: ${file(./serverless.env.yml):dev.OAUTH_ACCESS_TOKEN}
    SLACK_VERIFICATION_TOKEN: ${file(./serverless.env.yml):dev.SLACK_VERIFICATION_TOKEN}
    SLACK_ADMINS: ${file(./serverless.env.yml):dev.SLACK_ADMINS}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  slack:
    handler: build/slack.handler
    events:
      - http:
          path: slack
          method: post
          integration: lambda

  expireQuests:
    handler: build/index.expireQuests
    events:
      - schedule:
          rate: rate(10 minutes)

  remindAboutQuests:
      handler: build/index.remindAboutQuests
      events:
        - schedule:
            rate: rate(1 hour)

resources:
  Resources:
    SlackDynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        DeletionPolicy: Retain
        Properties:
          AttributeDefinitions:
            -
              AttributeName: id
              AttributeType: S
          KeySchema:
            -
              AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          TableName: ${file(./serverless.env.yml):dev.SLACK_TABLE_NAME}
    QuestsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${file(./serverless.env.yml):dev.QUESTS_TABLE_NAME}
    UserSettingsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${file(./serverless.env.yml):dev.USER_SETTINGS_TABLE_NAME}