service: quest-bank

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

  versionFunctions: false

  environment:
      QUESTS_TABLE_NAME: ${file(./serverless.env.yml):dev.QUESTS_TABLE_NAME}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  createQuest:
    handler: src/index.createQuest
    events:
      - http:
          path: quests
          method: post

  showQuest:
    handler: src/index.showQuest
    events:
      - http:
          path: quests/{id}
          method: get
          request:
            parameters:
              status: true

  indexQuests:
    handler: src/index.indexQuests
    events:
      - http:
          path: quests/{status}
          method: get
          request:
            parameters:
              status: false

  completeQuest:
    handler: src/index.completeQuest
    events:
      - http:
          path: quests/{id}/complete
          method: post

  destroyQuest:
    handler: src/index.destroyQuest
    events:
      - http:
          path: quests/{id}
          method: delete
          request:
            parameters:
              status: true

  expireQuests:
      handler: src/index.expireQuests
      events:
        - schedule:
            rate: rate(10 minutes)

resources:
  Resources:
    QuestsDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${file(./serverless.env.yml):dev.QUESTS_TABLE_NAME}